FROM registry.cn-shenzhen.aliyuncs.com/never615/centos-laravel:aliyun


# phpv8 v8js https://github.com/phpv8/v8js/wiki/Installing-on-CentOS-7-x64---PHP-7.3
RUN yum install -y subversion gcc gcc-c++ make chrpath redhat-lsb-core re2c

# Building a recent c++ compiler
RUN yum install -y bzip2 wget &&\
    cd /usr/local/src &&\
    wget https://www.mirrorservice.org/sites/sourceware.org/pub/gcc/releases/gcc-8.3.0/gcc-8.3.0.tar.gz &&\
    tar zxf gcc-8.3.0.tar.gz &&\
    cd gcc-8.3.0/ &&\
    ./contrib/download_prerequisites &&\
    ./configure --disable-multilib --enable-languages=c,c++ &&\
    make &&\
    make install &&\
    export LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/usr/local/lib64:/usr/lib64

# ---- v8js
RUN cd /usr/local &&\
# Add depot_tools
    git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git &&\
    export PATH=`pwd`/depot_tools:"$PATH" &&\
    # Build our v8 version
    cd /usr/local/src &&\
    fetch v8 &&\
    cd v8 &&\
    git checkout 7.5.288.23 # v8_version here &&\
    gclient sync &&\
    ./build/install-build-deps.sh &&\
    gn gen out.gn/library --args='use_custom_libcxx=false is_component_build=true is_debug=false target_cpu="x64" use_goma=false goma_dir="None" v8_enable_backtrace=true v8_enable_disassembler=true v8_enable_object_print=true v8_enable_verify_heap=true' &&\
    ninja -C out.gn/library libv8.so &&\
    # Move files we need to /opt/v8
    mkdir -p /opt/v8/{lib,include} &&\
    cp -v out.gn/library/lib*.so out.gn/library/*_blob.bin out.gn/library/icudtl.dat /opt/v8/lib/ &&\
    cp -vR include/* /opt/v8/include/ &&\
    # Update shared libraries when needed
    /sbin/ldconfig

# ---- php-v8js
RUN cd /usr/local/src &&\
    git clone https://github.com/phpv8/v8js.git &&\
    cd v8js &&\
    phpize &&\
    ./configure --with-v8js=/opt/v8 LDFLAGS="-lstdc++" &&\
    make -B &&\
    make test &&\
    make install &&\
    sed -i '$a extension=v8js.so'  /etc/php.ini
