FROM registry.cn-shenzhen.aliyuncs.com/never615/centos-laravel:aliyun


# phpv8 v8js https://github.com/phpv8/v8js/wiki/Installing-on-CentOS-7-x64---PHP-7.3
RUN yum install -y subversion gcc gcc-c++ make chrpath redhat-lsb-core re2c

# Building a recent c++ compiler
RUN yum install -y bzip2 wget &&\
    cd /usr/local/src &&\
    wget https://www.mirrorservice.org/sites/sourceware.org/pub/gcc/releases/gcc-8.3.0/gcc-8.3.0.tar.gz &&\
    tar zxf gcc-8.3.0.tar.gz &&\
    cd gcc-8.3.0/ &&\
    ./contrib/download_prerequisites &&\
    ./configure --disable-multilib --enable-languages=c,c++ &&\
    make &&\
    make install &&\
    export LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/usr/local/lib64:/usr/lib64
