name: Docker Image CI

on:
  push:
    branches: [ "rocky-build" ]
  pull_request:
    branches: [ "rocky-build" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rocky-swoole:$(date +%s)
